name: Run Simple Python Script

on:
  schedule:
    - cron:  '*/5 * * * *' # Every 5 mins. Ref https://crontab.guru/examples.html
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout repo content
      uses: actions/checkout@v2 # checkout the repository content to github runner.
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 #install the python needed
    - name: install requests
      run: pip install requests
    - name: execute run py script # run the run.py to get the latest data
      run: |
        python run.py
    - run: echo hello >> world.txt

    - uses: actions/upload-artifact@v2
      with:
        name: my-artifact
        path: world.txt
    
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        git add *
        git commit -m "Add changes" -a
    - name: Push changes
      uses: ad-m/github-push-action@main
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}